### ISSUE TITLE
As an SRAM admin, I want to be able to get an up-to-date list with contact persons os Orgs and Services

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SRAM-deploy#405]
Including service admins (role) and service adminitrative contact.

**Comment by baszoetekouw** [comment]
We cannot so this in SBS proper, as we need this list especially if SRAM is down. The script tot geneate the lists (CSV) is already in plsc, so we only need a way to expose the list externally.

The problem is that the machines that currently have access to the data are (on purpose) not reachable by other parts of the infrastructure.  So either we make one of those machines (probably the sbs hosts) reachable, or we store the credentials that give access to this info on the bhr13 host, or we modify SBS to output only the data we need using a specific scope.

Let's for now go for option 2; that makes it easy to migrate to 3 if we like, lateron.

**Comment by arnoutt** [comment]
Could you somehow upload (e.g., daily) the output of the script to a SURFdrive folder?

**Comment by mrvanes** [comment]
Tested and seen working
